apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - service.yaml
  - route.yaml
configMapGenerator:
  - name: nginx-conf
    files:
      - nginx.conf
  - name: rsyncd-conf
    files:
      - rsyncd.conf